
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Label labelTitulo;

	private global::Gtk.Entry entradaText;

	private global::Gtk.Button analizarButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(18));
		// Container child vbox1.Gtk.Box+BoxChild
		this.labelTitulo = new global::Gtk.Label();
		this.labelTitulo.HeightRequest = 47;
		this.labelTitulo.Name = "labelTitulo";
		this.labelTitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Ingresa una oracion para analizar");
		this.vbox1.Add(this.labelTitulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.labelTitulo]));
		w1.Position = 0;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entradaText = new global::Gtk.Entry();
		this.entradaText.HeightRequest = 48;
		this.entradaText.CanFocus = true;
		this.entradaText.Name = "entradaText";
		this.entradaText.IsEditable = true;
		this.entradaText.InvisibleChar = '•';
		this.vbox1.Add(this.entradaText);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entradaText]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.analizarButton = new global::Gtk.Button();
		this.analizarButton.HeightRequest = 74;
		this.analizarButton.CanFocus = true;
		this.analizarButton.Name = "analizarButton";
		this.analizarButton.UseUnderline = true;
		this.analizarButton.BorderWidth = ((uint)(15));
		this.analizarButton.Label = global::Mono.Unix.Catalog.GetString("Analizar");
		this.vbox1.Add(this.analizarButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.analizarButton]));
		w3.Position = 2;
		w3.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 600;
		this.DefaultHeight = 397;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
